WasteLess/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path,include
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.indexview,name='index'),
    path('/about',views.aboutusview,name='about'),
    path('/contact',views.contactview,name='contact'),
    path('/auth',views.authview,name='authy'), 
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
def indexview(request):
    return render(request,'main/index.html')

def aboutusview(request):
    return render(request,'main/aboutus.html')

def contactview(request):
    return render(request,'main/contactus.html')

def authview(request):
    return render(request,'main/login.html')

main/templates/main/aboutus.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel ="stylesheet" href= "{% static 'css/AboutUs.css' %}" >
{% endblock %}
{% block content %}
              <div class = "d-flex flex-lg-row flex-md-column flex-sm-column flex-xs-column flex-xl-row flex-grow-1 flex-shrink-0 flex-wrap justify-content-around align-items-center main">

                <div class="d-flex flex-column align-items-center justify-content-start card-article ">  
                  <h4>About Us</h4>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                  <div class="content">
                      <p>  The idea is to provide a platform where the sole users are the registered students of the institute.  Any user has an option to sell or to buy. </p>
                      <p> The user may put up any item such as a book, up for sale.  The user may also view all items available for sale, and request to buy it.  After selecting, the buyer will get an option to call the seller to continue the transaction or a cancel option to cancel the request.</p>  
                      <p> The buyer may now communicate with the seller to meet up in the college (this is the most viable option as both the buyer and the seller are present in the college) to check the validity of the item and finalize the transaction.  </p>
                    <p>  Another option available is to donate.  The donor can send a request to donate to the available causes.  The agency can accept the request.  After the request is accepted, contact information will  be exchanged between the sides.  Either side can contact the either to confirm the drop off.</p>
                        
                 </div>
            </div>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>WasteLess</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% block css %}
        
        {% endblock %}
        <link rel="stylesheet" href="{% static 'fontawesome-free-5.10.2-web/css/all.css' %}">
        
        
    </head>
    <body>
      <div style='min-height: 100%;position:relative;padding:0px;'>
          <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-light customNav">
              <a class="navbar-brand brand" href="#">
                  <img onclick='location.href="{% url 'main:index' %}";' src="{% static 'images/LOGOB.png' %}"></img></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>   
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
              
                <ul class="navbar-nav elements">
                  <li onclick='location.href="{% url 'main:index' %}";' class="nav-item active">
                    <a class="nav-link" href="#"> <p>Home</p> <span class="sr-only">(current)</span></a>
                  </li>
                  <li onclick='location.href="{% url 'main:about' %}";' class="nav-item">
                    <a class="nav-link" href="#"><p>About Us</p></a>
                  </li>
                  <li onclick='location.href="{% url 'main:contact' %}";' class='nav-item'>
                    <a class="nav-link" href="#"><p>Contact Us</p></a>
                  </li>
                  <li class="nav-item">
                    {% if user.is_authenticated %}
                    Hi {{ user.username }}!
                   {% else %}
                   <a class="nav-link" href="{% url 'login' %}"><p>Login/Register</p></a>
                   {% endif %}
                  </li>
                </ul>
              </div>
            </nav>

            {% block content %}

            {% endblock %}

              <div class="d-flex flex-column align-items-center bottom">
                  <div class = "d-flex flex-row justify-content-around align-items-center socials">
                    <i onclick="location.href = 'http://www.facebook.com';" class="fab fa-facebook"></i>
                    <i onclick="location.href = 'http://www.youtube.com';"class="fab fa-youtube"></i>
                    <i onclick="location.href = 'http://www.instagram.com';"class="fab fa-instagram"></i>
                    <i onclick="location.href = 'http://www.twitter.com';"class="fab fa-twitter"></i>
                  </div>
                  <hr class='break'/>
                  <p style='color:grey;font-size:0.7em;margin:10px;'>DEVELOPED BY CODE BENDERS</p>
              </div>

      </div>



              
                            
  
                
    </body>
</html>

main/templates/main/contactus.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel ="stylesheet" href= "{% static 'css/ContactUs.css' %}" >
{% endblock %}
{% block content %}
            <div class = "d-flex flex-lg-row flex-md-column flex-sm-column flex-xs-column flex-xl-row flex-grow-1 flex-shrink-0 flex-wrap justify-content-around align-items-center main">
                <div class="d-flex flex-column align-items-center justify-content-start card">
                        <div class="image">
                                <img  src="{% static 'images/Ashish.jpg' %}" alt="Ashish" style="width:100%">
                        </div>
                        <div class="content">
                            <h1>Ashish Tuteja</h1>
                            <p class="title">Team Leader</p>
                            <p>Code Benders</p>
                        </div>

                        <div class="links" style="margin: 24px 0;">
                                    <!-- <a href="#"><i class="fab fa-facebook-f"></i></a>  
                                    <a href="#"><i class="fas fa-envelope"></i></a>  
                                    <a href="#"><i class="fab fa-linkedin-in"></i></a>  -->
                            <i onclick="location.href = 'http://www.facebook.com';" class="fab fa-facebook"></i>
                            <i onclick="location.href = 'http://www.gmail.com';"class="fas fa-envelope"></i>
                            <i onclick="location.href = 'http://www.linkedin.com';"class="fab fa-linkedin-in"></i>
                          
                        </div>
                </div>

                <div class="d-flex flex-column align-items-center justify-content-start card">
                    <div class="image">
                            <img class="image" src="{% static 'images/Wankhede.jpg' %}" alt="Aditya" style="width:100%">
                        </div>
                    <div class="content">
                        <h1>Aditya Wankhede</h1>
                        <p class="title">Team Leader</p>
                        <p>Code Benders</p>
                    </div>
                    <div class="links" style="margin: 24px 0;">
                            <!-- <a href="#"><i class="fab fa-facebook-f"></i></a>  
                            <a href="#"><i class="fas fa-envelope"></i></a>  
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>  -->
                            <i onclick="location.href = 'http://www.facebook.com';" class="fab fa-facebook"></i>
                            <i onclick="location.href = 'http://www.gmail.com';"class="fas fa-envelope"></i>
                            <i onclick="location.href = 'http://www.linkedin.com';"class="fab fa-linkedin-in"></i>

                    </div>
                </div>

                <div class="d-flex flex-column align-items-center justify-content-start card">
                    <div class="image">
                            <img class="image" src="{% static 'images/jatin.jpg' %}" alt="Jatin" style="width:100%">
                    </div>
                    <div class="content">
                        <h1>Jatin Bansal</h1>
                        <p class="title">Team Leader</p>
                        <p>Code Benders</p>
                    </div>
                    <div class="links" style="margin: 24px 0;">
                        <!-- <a href="#"><i class="fab fa-facebook-f"></i></a>  
                        <a href="#"><i class="fas fa-envelope"></i></a>  
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>  -->
                        <i onclick="location.href = 'http://www.facebook.com';" class="fab fa-facebook"></i>
                        <i onclick="location.href = 'http://www.gmail.com';"class="fas fa-envelope"></i>
                        <i onclick="location.href = 'http://www.linkedin.com';"class="fab fa-linkedin-in"></i>

                    </div>
                </div>

                <div class="d-flex flex-column align-items-center justify-content-start card">
                    <div class="image"> 
                            <img class="image" src="{% static 'images/gaurav.jpg' %}" alt="Gaurav" style="width:100%">
                    </div>
                    <div class="content">
                        <h1>Gaurav Sachdeva</h1>
                        <p class="title">Team Leader</p>
                        <p>Code Benders</p>
                    </div>
                    <div class="links" style="margin: 24px 0;">
                        <!-- <a href="#"><i class="fab fa-facebook-f"></i></a>  
                        <a href="#"><i class="fas fa-envelope"></i></a>  
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>  -->
                        <i onclick="location.href = 'http://www.facebook.com';" class="fab fa-facebook"></i>
                        <i onclick="location.href = 'http://www.gmail.com';"class="fas fa-envelope"></i>
                        <i onclick="location.href = 'http://www.linkedin.com';"class="fab fa-linkedin-in"></i>

                    </div>
                </div>


                <div class="d-flex flex-column align-items-center justify-content-start card">
                    <div class="image">
                                <img class="image" src="{% static 'images/Vaibhav.jpg' %}" alt="Vaibhav" style="width:100%">
                        </div>
                        <div class="content">
                            <h1>Vaibhav Agarwal</h1>
                            <p class="title">Team Leader</p>
                            <p>Code Benders</p>
                        </div>
                        <div class="links" style="margin: 24px 0;">
                            <!-- <a href="#"><i class="fab fa-facebook-f"></i></a>  
                            <a href="#"><i class="fas fa-envelope"></i></a>  
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>  -->
                            <i onclick="location.href = 'http://www.facebook.com';" class="fab fa-facebook"></i>
                            <i onclick="location.href = 'http://www.gmail.com';"class="fas fa-envelope"></i>
                            <i onclick="location.href = 'http://www.linkedin.com';"class="fab fa-linkedin-in"></i>

                        </div>

                </div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel ="stylesheet" href= "{% static 'css/home.css' %}">
{% endblock %}
{% block content%}

              <div class = "d-flex flex-lg-row flex-md-column flex-sm-column flex-xs-column flex-xl-row flex-grow-1 flex-shrink-0 flex-wrap justify-content-around align-items-center main">

                <div onclick="location.href = 'buyer.html';"  class="d-flex flex-column align-items-center justify-content-start card">
                  <i class="fas fa-shopping-cart"></i>
                  <h5>Buy</h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                  <p>Explore the vast range of products our platform 
                    offers to your hearts content.</p>
                </div>
                <div onclick="location.href = 'seller.html';" class="d-flex flex-column align-items-center justify-content-start card">
                  <i class="fas fa-store"></i>
                  <h5>Sell</h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                  <p>Use our platform to advertise your product to 
                    hundreds of users.</p>
                </div>
                <div onclick="location.href = 'donate.html';"class="d-flex flex-column align-items-center justify-content-start card">
                    <i class="fas fa-donate"></i>
                  <h5>Donate</h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                  <p>We are partnered with multiple NGOs to allow you to 
                    give back to the community in an informed and precise manner.</p>
                </div>

{% endblock %}